#!/usr/bin/env bash

if [ "$SUPERVISOR_PHP_USER" != "root" ] && [ "$SUPERVISOR_PHP_USER" != "sail" ]; then
    echo "You should set SUPERVISOR_PHP_USER to either 'sail' or 'root'."
    exit 1
fi

# Adjust user ID if provided
if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

# Ensure /.composer exists and has appropriate permissions
if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Fix permissions for Laravel directories
if [ -d /var/www/html/storage ] && [ -d /var/www/html/bootstrap/cache ]; then
    echo "Adjusting permissions for Laravel directories..."
    chown -R sail:sail /var/www/html/storage /var/www/html/bootstrap/cache
    chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache
else
    echo "Laravel directories not found. Skipping permission adjustments."
fi

# Run commands if provided as arguments
if [ $# -gt 0 ]; then
    if [ "$SUPERVISOR_PHP_USER" = "root" ]; then
        exec "$@"
    else
        exec gosu $WWWUSER "$@"
    fi
else
    # Start Supervisor
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
