<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;

class LoginRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            'user_name' => 'required|string',
            'password' => 'required|string|min:6',
        ];
    }

    /**
     * @return array{
     *     user_name:string,
     *     password:string
     * }
     */
    public function validated($key = null, $default = null)
    {
        return parent::validated($key, $default); // TODO: Change the autogenerated stub
    }
}
