<?php

namespace App\Http\Requests;

use App\Enums\WorkSiteCompletionStatusEnum;
use App\Enums\WorkSiteReceptionStatusEnum;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\File;

class WorkSiteCreateRequest extends FormRequest
{
    /**
     * Get the validation rules that apply to the request.
     */
    public function rules(): array
    {
        return [
            'title' => 'required|string',
            'description' => 'required|string',
            'customer_id' => 'sometimes|integer',
            'category_id' => 'sometimes|integer',
            'parent_work_site_id' => 'nullable|integer|exists:work_sites,id',
            'contractor_id' => ['nullable', 'integer', 'exists:contractors,id'],
            'starting_budget' => 'sometimes|integer|min:0',
            'cost' => 'sometimes|integer|min:0',
            'address_id' => 'sometimes|integer|exists:addresses,id',
            'workers_count' => 'sometimes|integer|min:0',
            'receipt_date' => 'sometimes|date',
            'starting_date' => 'sometimes|date',
            'deliver_date' => 'sometimes|date',
            'reception_status' => ['sometimes', 'integer', Rule::in(WorkSiteReceptionStatusEnum::cases())],
            'completion_status' => ['sometimes', 'integer', Rule::in(WorkSiteCompletionStatusEnum::cases())],
            'resources' => 'sometimes|array',
            'resources.*.quantity' => 'sometimes|numeric',
            'resources.*.price' => 'sometimes|numeric',
            'resources.*.id' => 'sometimes|integer',
            'payments' => 'sometimes|array',
            'payments.*.payment_amount' => 'sometimes|numeric',
            'payments.*.payment_date' => ['sometimes', 'date_format:Y-m-d H:i'],
            'images' => ['sometimes'],
            'images.*' => ['sometimes', File::types(['jpeg', 'png', 'gif', 'webp'])
                ->max('2mb')],
        ];
    }

    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array{
     * title: string,
     * description: string,
     * customer_id?: int|null,
     * category_id?: int|null,
     * parent_work_site_id?: int|null,
     * contractor_id?: int|null,
     * starting_budget?: float|null,
     * cost?: float|null,
     * address_id?: int|null,
     * workers_count?: int|null,
     * receipt_date?: string|null,
     * starting_date?: string|null,
     * deliver_date?: string|null,
     * reception_status?: int|null,
     * completion_status?: int|null,
     * resources?: array{
     *      id:int,
     *      quantity:int,
     *      price:float
     *  }|null,
     * payments?: array{
     *      payment_amount:float,
     *      payment_date: string
     *  }|null,
     * images?: string|null
     * }
     */
    public function validated($key = null, $default = null): array
    {
        return parent::validated($key, $default); // TODO: Change the autogenerated stub
    }
}
