<?php

namespace App\Http\Requests;

use App\Enums\WorkSiteCompletionStatusEnum;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\File;

class WorkSiteUpdateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            'title' => 'sometimes|string',
            'description' => 'sometimes|string',
            'customer_id' => 'sometimes|integer',
            'category_id' => 'sometimes|integer',
            'parent_work_site_id' => 'nullable|int',
            'starting_budget' => 'sometimes|numeric|min:0',
            'cost' => 'sometimes|numeric|min:0',
            'address_id' => 'sometimes|integer|exists:addresses,id',
            'workers_count' => 'sometimes|integer|min:0',
            'receipt_date' => 'sometimes|date',
            'starting_date' => 'sometimes|date',
            'deliver_date' => 'sometimes|date',
            'completion_status' => ['sometimes', 'integer', Rule::in(WorkSiteCompletionStatusEnum::cases())],
            'reception_status' => 'sometimes|integer',
            'resources' => 'sometimes|array',
            'resources.*.quantity' => 'sometimes|numeric',
            'resources.*.price' => 'sometimes|numeric',
            'resources.*.id' => 'sometimes|integer',
            'images' => ['sometimes'],
            'images.*' => ['sometimes', File::types(['jpeg', 'png', 'gif', 'webp'])
                ->max('2mb')],
        ];
    }

    /**
     * @return array{
     * title: string |null,
     * description: string|null,
     * customer_id?: int|null,
     * category_id?: int|null,
     * parent_work_site_id?: int|null,
     * contractor_id?: float|null,
     * starting_budget?: float|null,
     * cost?: float|null,
     * address_id?: int|null,
     * workers_count?: int|null,
     * receipt_date?: string|null,
     * starting_date?: string|null,
     * deliver_date?: string|null,
     * reception_status?: int|null,
     * completion_status?: int|null,
     * resources?: array{
     *   id:int,
     *   quantity:int,
     *   price:float
     * }|null,
     * payments?: array{
     *   payment_amount:float,
     *   payment_date: string
     * }|null,
     * image?: string|null
     * }
     */
    public function validated($key = null, $default = null): array
    {
        return parent::validated($key, $default); // TODO: Change the autogenerated stub
    }
}
