### make Payment
POST http://localhost/api/v1/worksite/6/payment/create
Content-Type: application/json
Accept: application/json
Authorization: Bearer 2|3dWG9ogvwbceNUuR1BI3Abfhx5wRubEruYhz1xtU8ebf936b

{
    "payment_from_id":2,
    "payment_from_type":"clients",
    "payment_date":"2024-11-12 13:23",
    "payment_amount":500,
    "payment_type":1
}
